- name: Install Basic Packages
  become: true
  yum: pkg={{item}} state=present
  with_items:
   - epel-release
   - npm
   - nodejs
   - vim
   - git

- name: Install Development Tools package group
  become: true
  yum:
    name: "@Development tools"
    state: present
