---
- name: Create symlink between python2.7 to python
  remote_user: root
  raw: ln -s /usr/local/bin/python2.7 /usr/bin/python
  ignore_errors: yes

- name: Create Ansible User
  remote_user: root
  user:
    name: ansible
    state: present
  
- name: Add Ansible User SSH Public Key
  remote_user: root
  authorized_key:
    user: ansible
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+g68qreSoiG66ItvI9ggwC7yZdgUZcPnHAjbHtGyTgLaQTZZx7SYewMhGN3uhYAOXSnAKpaZh1Z+HNkcbuJJfpGGJm/Yp18JYAHyAKG/kuKFxeEmmB0ECfdwg16cDZlBCjSq85afGqQT0J0WwnFgPs3or9zGkWOqAsHI4PaKsXxGhB3xnwRvitli0dYiFvox/3tpwJwfx5WR/82IYvX9ATu5YFMYZ1MO1HUyAtMngRx1kRHujOGCQJ3cr/qgf0dGKTsIl+G6k1+MbnPlcqUFBnXLl3i8hvnYAO+e0f1xGd4odG85CKBL7F7ltKDl8oKAuuEI6QkHLFQxAiF1vbJkz dany0@do-nyc1.310networks.com
    state: present
  
- name: Ensure ansible user is in /usr/local/etc/sudoers with no pass required
  remote_user: root
  lineinfile:
    dest: /usr/local/etc/sudoers
    state: present
    regexp: '^ansible ALL\='
    line: 'ansible ALL=(ALL) NOPASSWD:ALL'

- name: Disable Root Login
  remote_user: root
  lineinfile:  
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  register: ssh_config

- name: Remove without password
  remote_user: root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: absent
    regexp: '^PermitRootLogin without-password'
  register: ssh_config

- name: Disable Password Authentication
  remote_user: root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    insertafter: EOF
  register: ssh_config

- name: Copy over 310 Networks SSH Welcome Banner
  remote_user: root
  copy:
    src: /etc/ansible/files/misc/sshd-banner
    dest: /etc/ssh/sshd-banner
    owner: root
    group: wheel

- name: Use 310 Networks SSH Banner
  remote_user: root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^Banner'
    line: 'Banner /etc/ssh/sshd-banner'
    insertafter: EOF
  register: ssh_config

- name: Restart SSH
  remote_user: root
  service:
    name: sshd
    state: restarted
