- name: Clone node-cryptonote-pool repo
  become: true
  git:
    repo: https://github.com/zone117x/node-cryptonote-pool.git
    dest: ~/pool
    clone: yes

- name: Download latest stable version of Redis
  become: true
  get_url:
    url: http://download.redis.io/redis-stable.tar.gz
    dest: /tmp/redis-stable.tar.gz

- name: Unarchive Redis into root dir
  become: true
  unarchive:
    src: /tmp/redis-stable.tar.gz
    dest: ~/
    remote_src: yes

- name: Install Redis
  become: true
  raw: cd ~/redis-stable/ && make install

- name: Start Redis
  command: redis-server

- name: Update node-cryptonote-pool config
  become: true
  template:
    src: ../templates/node-cryptonote-pool/config.json.j2
    dest: /root/pool/config.json
    owner: root
    group: wheel

- name: Update pool website config
  become: true
  template:
    src: ../templates/node-cryptonote-pool/website_config.js.j2
    dest: /root/pool/website_example/config.js
    owner: root
    group: wheel

- name: Update package.json with updated multi-hashing and cryptonote-util git repos
  become: true
  template:
    src: ../templates/node-cryptonote-pool/package.json.j2
    dest: /root/pool/package.json
    owner: root
    group: wheel

- name: npm update cryptonote pool
  become: true
  npm:
    path: ~/pool
    state: latest
